# 服务器信息
server:
  address: 192.168.8.100
  port: 5000

# spring应用信息
spring:
  application:
    name: monitor-admin-server

  # security安全配置
  security:
    user:
      name: admin
      password: 123456

  # cloud设置
  cloud:
    # 负载均衡：关闭负载均衡器ribbon选项，因为ribbon也包含了负载均衡器，两个有冲突?
    # 会导致无法调用或转发服务请求
    loadbalancer:
      ribbon:
        enabled: false

# eureka注册中心配置
eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      # eureka-server服务注册中心地址，如果是集群，可以用逗号隔开
      defaultZone: http://192.168.8.100:2000/eureka
  instance:
    hostname: ${server.address}
    lease-renewal-interval-in-seconds: 10
    # 健康检查url
    health-check-url-path: /actuator/health
    # 定义注册到eureka中的服务实例instance-id，在eureka后台显示
    instance-id: ${spring.application.name}:${server.address}:${server.port}
    # SpringBootAdmin登录账号密码
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

# actuator应用监控配置
management:
  # 配置端点
  endpoint:
    health:
      show-details: ALWAYS # 健康信息端点显示详情
    shutdown:
      enabled: true # 开启关闭应用的断点

  # 曝露端点
  endpoints:
    web:
      exposure:
        include: "*" # 曝露所有端点

logging:
  level:
    de.codecentric.boot.admin.server: DEBUG