# 服务器信息
server:
  address: 192.168.8.100
  port: 3000

# spring应用信息
spring:
  application:
    name: monitor-turbine-server

  # cloud设置
  cloud:
    # 负载均衡：关闭负载均衡器ribbon选项，因为ribbon也包含了负载均衡器，两个有冲突?
    # 会导致无法调用或转发服务请求
    loadbalancer:
      ribbon:
        enabled: false

# eureka注册中心配置
eureka:
  client:
    serviceUrl:
      # eureka-server服务注册中心地址，如果是集群，可以用逗号隔开
      defaultZone: http://192.168.8.100:2000/eureka
  instance:
    hostname: ${server.address}
    # 定义注册到eureka中的服务实例instance-id，在eureka后台显示
    instance-id: ${spring.application.name}:${server.address}:${server.port}

# actuator应用监控配置
management:
  # 配置端点
  endpoint:
    health:
      show-details: ALWAYS # 健康信息端点显示详情
    shutdown:
      enabled: false # 关闭（默认）应用的端点

  # 曝露端点
  endpoints:
    web:
      exposure:
        include: "*" # 曝露所有端点

# hystrix配置
# 被监控应用（user-service）熔断数据流接口的主机列表，否则配置聚合监控面板时（/turbine.stream）无法获取获取监控数据流时将报错
# 主机地址 + turbine.instance-url-suffix为完成的熔断监控数据流调用接口
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"

# turbine配置：监控应用(服务消费方)的熔断情况
# 下面的例子，聚合监控user-service和blog-service对日志服务log-service调用的熔断情况
turbine:
  combine-host-port: true
  app-config: user-service, blog-service, log-service # 多个应用使用逗号隔开
  cluster-name-expression: new String("default")
  aggregator:
    cluster-config: default
  instance-url-suffix: /actuator/hystrix.stream # 调用被监控应用的数据流接口地址，缺省/actuator/hystrix.stream

logging:
  level:
    org.springframework.cloud.netflix: DEBUG