# spring应用信息
spring:
  # cloud设置
  cloud:
    # 负载均衡：关闭负载均衡器ribbon选项，因为ribbon也包含了负载均衡器，两个有冲突?
    # 会导致无法调用或转发服务请求
    loadbalancer:
      ribbon:
        enabled: false
    # gateway网关设置
    gateway:
      # 使用服务发现
      discovery:
        locator:
          enabled: false # 不注册服务为名的路由
          lowerCaseServiceId: true # 服务名小写
      routes:
        - id : eureka-server
          uri: lb://eureka-server # 启用服务发现后，这里填写 负载均衡://服务名，不需要写具体具体的主机地址
          predicates:
            - Path=/eureka/** # 路径断言，凡是以/eureka开头的前缀都路由到eureka-server服务处理

        - id : monitor-admin-server
          uri: lb://monitor-admin-server
          predicates:
            - Path=/monitor/admin/** # 路径断言，配合StripPrefix使用删除/monitor/admin再转发
          filters:
            - StripPrefix=2 # 截掉Path的第2层目录：/monitor/admin

        - id : monitor-turbine-server
          uri: lb://monitor-turbine-server
          predicates:
            - Path=/monitor/turbine/**
          filters:
            - StripPrefix=2

        - id : user-service
          uri: lb://user-service
          predicates:
            - Path=/api/*/users/**
            #- Header=Authorization,* # 必须有认证授权请求头
          filters:
            - StripPrefix=2
            - name: RequestRateLimiter # 服务限流
              args:
                key-resolver: '#{@uriKeyResolver}' # 根据uri进行限流，uriKeyResolver对象的bean定义在配置文件中
                redis-rate-limiter:
                  replenishRate: 10 # 令牌桶每秒的平均填充速度
                  burstCapacity: 30 # 令牌桶总容量

        - id : blog-service
          uri: lb://blog-service
          predicates:
            - Path=/api/*/blogs/**
          filters:
            - StripPrefix=2
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@uriKeyResolver}'
                redis-rate-limiter:
                  replenishRate: 10
                  burstCapacity: 30

        - id : log-service
          uri: lb://log-service
          predicates:
            - Path=/api/*/logs/**
          filters:
            - StripPrefix=2
  # 用于服务限流,储存令牌
  redis:
    host: 192.168.8.190
    port: 6379
    database: 0

logging:
  level:
    org.springframework.cloud.gateway: DEBUG