# spring应用信息
spring:
  # cloud设置
  cloud:
    config:
      override-none: true # 本地配置覆盖远程节点即配置中心的配置，如果存在相同属性
    loadbalancer:
      ribbon:
        enabled: false # 关闭负载均衡器的ribbon，解决一些警告
  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    address: localhost:3306
    url: jdbc:mysql://${spring.datasource.address}/vblog?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: coffee
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  #security安全配置：账号密码配置在内存，一般会放在数据库中管理
  #  security:
  #    user:
  #      name: admin
  #      password: 123456