spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    address: 192.168.8.183:3306
    url: jdbc:mysql://${spring.datasource.address}/vblog?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: coffee
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
management:
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.security: DEBUG