# spring应用信息
spring:
  # cloud设置
  cloud:
    # 负载均衡：关闭负载均衡器ribbon选项，因为ribbon也包含了负载均衡器，两个有冲突?
    # 会导致无法调用或转发服务请求
    loadbalancer:
      ribbon:
        enabled: false

# actuator应用监控配置
management:
  # 配置端点
  endpoint:
    health:
      show-details: ALWAYS # 健康信息端点显示详情
    shutdown:
      enabled: false # 关闭（默认）应用的端点

  # 曝露端点
  endpoints:
    web:
      exposure:
        include: "*" # 曝露所有端点

# feign配置：远程调用开启熔断功能，否则fallback指定的Mock无法启用，另外需要注意首次调用超时问题
feign:
  hystrix:
    enabled: true

# hystrix配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000 # 调用超时时间默认1秒，设为15秒避免首次调用超时而熔断
  # 允许调用数据流/actuator/hystrix.stream的主机列表
  dashboard:
    proxy-stream-allow-list: ${server.address}