# spring应用信息
spring:
  # cloud设置
  cloud:
    config:
      override-none: true # 本地配置覆盖远程节点即配置中心的配置，如果存在相同属性
    loadbalancer:
      ribbon:
        enabled: false # 关闭负载均衡器的ribbon，解决一些警告

# feign配置：远程调用开启熔断功能，否则fallback指定的Mock无法启用，另外需要注意首次调用超时问题
feign:
  hystrix:
    enabled: true

# hystrix配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000 # 调用超时时间默认1秒，设为15秒避免首次调用超时而熔断
  # 允许调用数据流/actuator/hystrix.stream的主机列表
  dashboard:
    proxy-stream-allow-list: ${server.address}