# 服务器信息
server:
  address: 192.168.8.115
  port: 2000

# spring应用信息
spring:
  application:
    name: eureka-server

  # cloud设置
  cloud:
    # 负载均衡：关闭负载均衡器ribbon选项，因为ribbon也包含了负载均衡器，两个有冲突?
    # 会导致无法调用或转发服务请求
    loadbalancer:
      ribbon:
        enabled: false

# eureka配置
eureka:
  server:
    enable-self-preservation: false # 关闭自我保护机制：剔除失效的服务节点
    eviction-interval-timer-in-ms: 30000 # 清理无效服务节点的时间间隔，默认时60秒
  client:
    register-with-eureka: true  # 否向将自身注册为服务：注册为服务，以便spring-boot-admin可以进行健康监控
    fetch-registry: false  # 是否从eureka拉取注册信息
    serviceUrl:  # 曝露注册中心地址。如果搭建集群，这里填写集群中其它eureka节点的地址，多个用逗号隔开
      defaultZone: http://${server.address}:${server.port}/eureka
  instance:
    hostname: ${server.address}  # 集群时使用
    instance-id: ${spring.application.name}:${server.address}:${server.port}

# actuator应用监控配置
management:
  # 配置端点
  endpoint:
    health:
      show-details: ALWAYS # 健康信息端点显示详情
    shutdown:
      enabled: false # 关闭（默认）应用的端点

  # 曝露端点
  endpoints:
    web:
      exposure:
        include: "*" # 曝露所有端点

# 日志配置
logging:
  level:
    com.fandou.coffee.learning.springcloud.eureka: DEBUG